# https://bazel-contrib.github.io/rules_foreign_cc/cmake.html
load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_cc//cc:objc_library.bzl", "objc_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:private"],
)

cmake(
    name = "sdl3_shared",
    lib_source = ":all_srcs",
    defines = select({
        "@bazel_tools//src/conditions:darwin": [
            "CMAKE_OSX_DEPLOYMENT_TARGET=10.13",
        ],
        "//conditions:default": []
    }),
    out_include_dir = "include",
    out_interface_libs = select({
        "@bazel_tools//src/conditions:windows": ["SDL3.lib"],
        "//conditions:default": []
    }),
    out_shared_libs = select({
        "@bazel_tools//src/conditions:darwin": ["libSDL3.0.dylib"],
        "@bazel_tools//src/conditions:linux": ["libSDL3.so.0"],
        "@bazel_tools//src/conditions:windows": ["SDL3.dll"],
        #TODO: WASM -sSIDE_MODULE https://emscripten.org/docs/compiling/Dynamic-Linking.html
        # "@platforms//cpu:wasm32": ["libSDL3.so"]
        "//conditions:default": []
    }),
    visibility = ["//visibility:public"],
)

cmake(
    name = "sdl3_static_base",
    lib_source = ":all_srcs",
    generate_args = [
        "-DSDL_STATIC=true",
        "-DSDL_SHARED=false",
        "-DSDL_PTHREADS=true",
    ] + select({
        "@platforms//cpu:wasm32": ["-DEMSCRIPTEN=true"],
        "@platforms//os:wasi": ["-DEMSCRIPTEN=true"],
        "//conditions:default": []
    }),
    defines = select({
        "@bazel_tools//src/conditions:darwin": [
            "CMAKE_OSX_DEPLOYMENT_TARGET=10.13",
        ],
        "//conditions:default": []
    }),
    out_include_dir = "include",
    out_static_libs = select({
        "@bazel_tools//src/conditions:windows": ["SDL3-static.lib"],
        "//conditions:default": ["libSDL3.a"],
    }),
    visibility = ["//visibility:private"],
)

# Workaround for linkopts in cmake rule w/ space isn't passed to dependents correctly
cc_library(
    name = "sdl3_static",
    deps = [":sdl3_static_base"],
    # link options to be passed up to the dependencies of this library
    linkopts = select({
        "@bazel_tools//src/conditions:darwin": [
            "-framework", "CoreGraphics",
            "-framework", "CoreAudio",
            "-framework", "CoreHaptics",
            "-framework", "CoreMedia",
            "-framework", "CoreVideo",
            "-framework", "AVFoundation",
            "-framework", "AudioToolbox",
            "-framework", "ForceFeedback",
            "-framework", "GameController",
            "-framework", "IOKit",
            "-framework", "Carbon",
            "-framework", "Metal",
            "-framework", "AppKit",
            "-framework", "QuartzCore",
            "-framework", "UniformTypeIdentifiers",
        ],
        "@bazel_tools//src/conditions:windows": [
            "User32.lib",   # Window functions (CreateWindow, MessageBox, etc.)
            "Gdi32.lib",    # GDI functions (CreateDC, SelectObject, BitBlt, GetDeviceCaps, etc.)
            "Advapi32.lib", # Registry functions (RegOpenKeyExW, etc.)
            "Shell32.lib",  # Shell functions (ShellExecuteW, SHGetFolderPathW, etc.)
            "Ole32.lib",    # COM functions (CoInitializeEx, CoCreateInstance, etc.)
            "Oleaut32.lib", # OLE Automation functions (IDispatch, VARIANT, SysFreeString, etc.)
            "Imm32.lib",    # IME Input Method Manager functions
            "Winmm.lib",    # Windows Multimedia functions (timeBeginPeriod, etc.)
            "Version.lib",  # Version functions (GetFileVersionInfo, etc.)
            "Setupapi.lib", # Device Setup API functions (SetupDiGetClassDevs, etc.)
            #"Cfgmgr32.lib", # Configuration Manager functions
        ],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
)

# Pure Bazel declarations for platforms
objc_library(
    name = "sdl3-darwin",
    srcs = glob([
        "src/*.c",
        "src/atomic/*.c",
        "src/audio/*.c",
        "src/camera/*.c",
        "src/core/*.c",
        "src/cpuinfo/*.c",
        "src/dynapi/*.c",
        "src/events/*.c",
        "src/io/*.c",
        "src/io/generic/*.c",
        "src/filesystem/*.c",
        "src/gpu/*.c",
        "src/joystick/*.c",
        "src/haptic/*.c",
        "src/hidapi/*.c",
        "src/locale/*.c",
        "src/main/*.c",
        "src/misc/*.c",
        "src/power/*.c",
        "src/render/*.c",
        "src/render/*/*.c",
        "src/sensor/*.c",
        "src/stdlib/*.c",
        "src/storage/*.c",
        "src/thread/*.c",
        "src/time/*.c",
        "src/timer/*.c",
        "src/video/*.c",
        "src/video/yuv2rgb/*.c",
    ]) + select({
        "@bazel_tools//src/conditions:darwin": glob([
            "src/main/generic/*.c",
            "src/time/unix/*.c",
            "src/timer/unix/*.c",
            "src/power/macos/*.c",
            "src/loadso/dlopen/*.c",
            "src/misc/macos/*.m",

            "src/misc/macos/*.m",
            "src/dialog/*.c",
            "src/dialog/cocoa/*.m",

            "src/filesystem/posix/*.c",
            "src/filesystem/cocoa/*.m",

            "src/locale/macos/*.m",

            "src/audio/dummy/*.c",
            "src/audio/disk/*.c",
            "src/audio/coreaudio/*.m",

            "src/camera/dummy/*.c",
            "src/camera/coremedia/*.m",

            "src/video/dummy/*.c",
            "src/video/offscreen/*.c",
            "src/video/cocoa/*.m",

            "src/storage/generic/*.c",

            "src/joystick/virtual/*.c",
            "src/joystick/hidapi/*.c",
            "src/joystick/apple/*.m",
            "src/joystick/darwin/*.c",

            "src/render/metal/*.m",
            "src/gpu/metal/*.m",
            "src/gpu/vulkan/*.c",

            "src/thread/pthread/*.c",
            "src/process/*.c",
            "src/process/posix/*.c",

            "src/sensor/dummy/*.c",
            "src/sensor/coremotion/*.m",

            "src/haptic/darwin/*.c",

            "src/tray/*.c",
            "src/tray/cocoa/*.m",
        ]),
    }),
    hdrs = glob(["include/**/*.h"]),
    copts = [
        # lot of warning: '<name>' is deprecated: first deprecated in macOS 13.0 - Use MTLGPUFamily instead [-Wdeprecated-declarations]
        "-Wno-deprecated-declarations",
        # SDL_tray.m:379:98: warning: undeclared selector 'menu:' [-Wundeclared-selector]
        "-Wno-undeclared-selector",
    ],
    includes = [
        "src",
        "include",
        "include/build_config",
        "src/video/khronos",
    ],
    linkopts = [
        "-framework", "CoreGraphics",
        "-framework", "CoreAudio",
        "-framework", "CoreHaptics",
        "-framework", "CoreMedia",
        "-framework", "CoreVideo",
        "-framework", "AVFoundation",
        "-framework", "AudioToolbox",
        "-framework", "ForceFeedback",
        "-framework", "GameController",
        "-framework", "IOKit",
        "-framework", "Carbon",
        "-framework", "Metal",
        "-framework", "AppKit",
        "-framework", "QuartzCore",
        "-framework", "UniformTypeIdentifiers",
    ],
    visibility = ["//visibility:private"],
)

# Convenience library that depends on different static declarations
cc_library(
    name = "sdl3",
    deps = select({
        "@bazel_tools//src/conditions:darwin": [":sdl3-darwin"],
        "//conditions:default": [":sdl3_static"], # cmake static version
    }),
    visibility = ["//visibility:public"],
)
